const {
  createAirBookingRequestBodyForCommonAPI,
} = require("./helpers/common-air-booking.helper");

const request = {
  SearchRequest: {
    Authentication: {
      CompanyId: "6555f84c991eaa63cb171a9f",
      UserId: "65cdfd5203e867cfc4153aa9",
      BookedBy: "6555f84d991eaa63cb171aa9",
      CredentialType: "TEST",
      SalesChannel: "B2B",
      TraceId: "ee387ae2-395f-41ae-9667-e4055fb8c650",
      AgencyId: "65cdfd5203e867cfc4153aa7",
    },
    TypeOfTrip: "ONEWAY",
    Segments: [
      {
        Origin: "DEL",
        Destination: "DOH",
        OriginName: "Delhi",
        DestinationName: "Doha",
        DepartureDate: "2025-02-28",
        DepartureTime: "00:01",
        DepartureTimeTo: "23:59",
        ClassOfService: "Economy",
      },
    ],
    PaxDetail: {
      Adults: 1,
      Child: 0,
      Infants: 0,
      Youths: 0,
    },
    Flexi: 0,
    Direct: 3,
    ClassOfService: "Economy",
    Airlines: ["QR"],
    TravelType: "International",
    FareFamily: [],
    RefundableOnly: false,
  },
  PassengerPreferences: {
    GstData: {
      gstNumber: "",
      gstName: "",
      gstmobile: "",
      gstEmail: "",
      gstAddress: "",
      GSTState: "",
      GSTPinCode: "",
      isAgentGst: false,
    },
    PaxEmail: "NASIR@DIGITRAVELSOLUTIONS.COM",
    PaxMobile: "9971638007",
    Passengers: [
      {
        PaxType: "ADT",
        passengarType: "Adult",
        passengarSerialNo: 1,
        Title: "MS",
        FName: "APARAJITA",
        LName: "SINGH",
        Gender: "Female",
        Dob: "2013-02-20",
        viewOnlyIssuedDate: "2025-01-01",
        viewOnlyExpiryDate: "2025-03-26",
        Optional: {
          ticketDetails: [
            {
              ticketNumber: "",
              src: "DEL",
              des: "DOH",
            },
          ],
          PassportNo: "A3456789",
          PassportExpiryDate: "2025-03-25T18:30:00.000Z",
          PassportIssuedDate: "2024-12-31T18:30:00.000Z",
          FrequentFlyerNo: "",
          Nationality: "IN",
          ResidentCountry: "IN",
          invalidPassportExpiryDate: false,
        },
        Meal: [],
        Baggage: [],
        Special: null,
        Seat: [],
        status: "",
        totalBaggagePrice: 0,
        totalMealPrice: 0,
        totalSeatPrice: 0,
      },
    ],
  },
  paymentMethodType: "Wallet",
  ItineraryPriceCheckResponses: [
    {
      UniqueKey: "709668443",
      FreeSeat: false,
      FreeMeal: true,
      SessionKey: "SP2F-13279624610849515366",
      CarbonEmission: "",
      InPolicy: false,
      IsRecommended: true,
      UID: "3e18fb1b-c97c-4453-abff-9b23cbfb1b36",
      BaseFare: 21880,
      Taxes: 14458,
      TotalPrice: 36338,
      OfferedPrice: 36338,
      GrandTotal: 36338,
      Currency: "INR",
      FareType: "RP",
      Stop: 0,
      IsVia: false,
      TourCode: "",
      PricingMethod: "",
      FareFamily: "Regular Fare",
      PromotionalFare: false,
      FareFamilyDN: null,
      PromotionalCode: "",
      PromoCodeType: "",
      RefundableFare: true,
      IndexNumber: 0,
      Provider: "1AN",
      ValCarrier: "QR",
      LastTicketingDate: "",
      TravelTime: "0d:4h:40m",
      PriceBreakup: [
        {
          PassengerType: "ADT",
          NoOfPassenger: 1,
          Tax: 14458,
          BaseFare: 21880,
          TaxBreakup: [
            {
              TaxType: "YQ",
              Amount: 10309,
            },
            {
              TaxType: "YR",
              Amount: 945,
            },
            {
              TaxType: "IN",
              Amount: 62,
            },
            {
              TaxType: "K3",
              Amount: 1657,
            },
            {
              TaxType: "P2",
              Amount: 1217,
            },
            {
              TaxType: "WO",
              Amount: 91,
            },
            {
              TaxType: "PZ",
              Amount: 177,
            },
          ],
          AirPenalty: [],
          CommercialBreakup: [
            {
              CommercialType: "Discount",
              Amount: 0,
              SupplierType: "TMC",
              newAmount: 0,
            },
            {
              CommercialType: "TDS",
              onCommercialApply: "Discount",
              Amount: 0,
              SupplierType: "TMC",
            },
          ],
          AgentMarkupBreakup: {
            BookingFee: 0,
            Basic: 0,
            Tax: 0,
          },
          key: "1A_TPID_CAESHVNQMkYtMTMyNzk2MjQ2MTA4NDk1MTUzNjYtMS0x~T1",
          OI: [],
        },
        {},
        {},
      ],
      Sectors: [
        {
          IsConnect: false,
          AirlineCode: "QR",
          AirlineName: "Qatar Airways",
          Class: "N",
          CabinClass: "Economy Standard",
          BookingCounts: "",
          NoSeats: 9,
          FltNum: "4781",
          EquipType: "",
          FlyingTime: "0d:4h:40m",
          TravelTime: "0d:4h:40m",
          TechStopOver: null,
          layover: "",
          Status: "",
          OperatingCarrier: "6E",
          MarketingCarrier: null,
          BaggageInfo: "25KG",
          HandBaggage: "7KG",
          TransitTime: null,
          MealCode: null,
          key: "SEG5~NLR4I1RQ~",
          Distance: "",
          ETicket: "No",
          ChangeOfPlane: "",
          ParticipantLevel: "",
          OptionalServicesIndicator: false,
          AvailabilitySource: "",
          Group: "0",
          LinkAvailability: false,
          PolledAvailabilityOption: "",
          FareBasisCode: "NLR4I1RQ",
          HostTokenRef: "",
          APISRequirementsRef: "",
          Departure: {
            Terminal: "3",
            Date: "2025-02-28",
            Time: "16:40",
            Day: "Friday",
            DateTimeStamp: "2025-02-28T16:40:00",
            Code: "DEL",
            Name: "Indira Gandhi International Airport",
            CityCode: "DEL",
            CityName: "Delhi",
            CountryCode: "IN",
            CountryName: "India",
          },
          Arrival: {
            Terminal: "",
            Date: "2025-02-28",
            Time: "18:50",
            Day: "Friday",
            DateTimeStamp: "2025-02-28T18:50:00",
            Code: "DOH",
            Name: "Hamad International Airport",
            CityCode: "DOH",
            CityName: "Doha",
            CountryCode: "QA",
            CountryName: "Qatar",
          },
          OI: [],
          ProductClass: "",
          modifiedTravelTime: "04:40",
          travelDaysCount: 0,
          modifiedLayoverTime: "",
          airlineLogo: "https://agentapi.kafilaholidays.in/assets/logo/QR.png",
        },
      ],
      FareRule: null,
      HostTokens: null,
      Key: "TO5VQQPs0gTwy7pqjviX5TMA.1_1A_8268f0a9-abfa-4d21-be71-d0d03283816b_1A_1A_TPID_Ch8SG1NQMkYtMTMyNzk2MjQ2MTA4NDk1MTUzNjYtMRgB",
      SearchID: "0c232f4b-d6ca-4df1-b29c-a75c9ced3de2",
      TRCNumber: null,
      TraceId: "ee387ae2-395f-41ae-9667-e4055fb8c650",
      OI: null,
      SelectedFlight: {
        PId: 1,
        Id: 1,
        TId: 1,
        FCode: "QR",
        FName: "Qatar Airways",
        FNo: "4781",
        DDate: "2025-02-28T16:40:00",
        ADate: "2025-02-28T18:50:00",
        Dur: "0d:4h:40m",
        Stop: 0,
        Seats: 9,
        Sector: "DEL,DOH",
        Itinerary: [
          {
            Id: 0,
            Src: "DEL",
            SrcName: "Delhi",
            Des: "DOH",
            DesName: "Doha",
            FLogo: "",
            FCode: "QR",
            FName: "Qatar Airways",
            FNo: "4781",
            DDate: "2025-02-28T16:40:00",
            ADate: "2025-02-28T18:50:00",
            DTrmnl: "3",
            ATrmnl: "",
            DArpt: "Indira Gandhi International Airport",
            AArpt: "Hamad International Airport",
            Dur: "0d:4h:40m",
            layover: "",
            Seat: 9,
            FClass: "N",
            PClass: "",
            FBasis: "NLR4I1RQ",
            FlightType: "",
            OI: null,
          },
        ],
        Fare: {
          GrandTotal: 36338,
          BasicTotal: 21880,
          YqTotal: 0,
          TaxesTotal: 14458,
          Adt: {
            Basic: 21880,
            Yq: 0,
            Taxes: 14458,
            Total: null,
          },
          Chd: null,
          Inf: null,
          OI: null,
        },
        FareRule: null,
        Alias: "Regular Fare",
        FareType: null,
        PFClass: null,
        OI: null,
        Offer: null,
        Deal: {
          NETFARE: 36338,
          TDISC: 0,
          TDS: 0,
          GST: 0,
          DISCOUNT: {
            DIS: 0,
            SF: 0,
            PDIS: 0,
            CB: 0,
          },
        },
      },
      FareDifference: {
        FareDifference: 0,
        NewFare: 36338,
        OldFare: 36338,
        Journeys: [
          {
            Security: "",
            IPaxkey: "",
            TotalFare: 36338,
            BasicTotal: 21880,
            YqTotal: 0,
            TaxTotal: 14458,
            Segments: [
              {
                PaxType: "ADT",
                TaxBreakup: [
                  {
                    CType: "FarePrice",
                    CCode: "",
                    Amt: 21880,
                  },
                  {
                    CType: "YQ",
                    CCode: "YQ",
                    Amt: 10309,
                  },
                  {
                    CType: "YR",
                    CCode: "YR",
                    Amt: 945,
                  },
                  {
                    CType: "IN",
                    CCode: "IN",
                    Amt: 62,
                  },
                  {
                    CType: "K3",
                    CCode: "K3",
                    Amt: 1657,
                  },
                  {
                    CType: "P2",
                    CCode: "P2",
                    Amt: 1217,
                  },
                  {
                    CType: "WO",
                    CCode: "WO",
                    Amt: 91,
                  },
                  {
                    CType: "PZ",
                    CCode: "PZ",
                    Amt: 177,
                  },
                ],
              },
              {},
              {},
            ],
          },
        ],
      },
      Error: {
        Status: null,
        Result: null,
        ErrorMessage: "",
        ErrorCode: null,
        Location: "SELL",
        WarningMessage: "",
        IsError: false,
        IsWarning: false,
      },
      IsFareUpdate: false,
      IsAncl: false,
      Param: {
        Trip: "D1",
        Adt: 1,
        Chd: 0,
        Inf: 0,
        Sector: [
          {
            Src: "DEL",
            Des: "DOH",
            DDate: "2025-02-28",
          },
        ],
        PF: "",
        PC: "",
        Routing: "ALL",
        Ver: "1.0.0.0",
        Auth: {
          AgentId: null,
          Token: null,
        },
        Env: "D",
        Module: "B2B",
        OtherInfo: {
          PromoCode: "",
          FFlight: "",
          FareType: "",
          TraceId: "ee387ae2-395f-41ae-9667-e4055fb8c650",
          IsUnitTesting: false,
          TPnr: false,
          FAlias: null,
          IsLca: false,
        },
      },
      GstData: {
        IsGst: false,
        GstDetails: {
          Name: "",
          Address: "",
          Email: "",
          Mobile: "",
          Pin: "",
          State: "",
          Type: "",
          Gstn: "",
          isAgentGst: false,
        },
      },
      advanceAgentMarkup: {
        adult: {
          baseFare: 0,
          taxesFare: 0,
          feesFare: 0,
          gstFare: 0,
        },
        child: {
          baseFare: 0,
          taxesFare: 0,
          feesFare: 0,
          gstFare: 0,
        },
        infant: {
          baseFare: 0,
          taxesFare: 0,
          feesFare: 0,
          gstFare: 0,
        },
      },
      oldModifiedTotalPrice: 36338,
      modifiedRefundableFlag: "R",
      seatsAvlCounts: 9,
      offeredPrice: 36338,
      modifiedTotalPrice: 36338,
      sectorCountString: "Non-Stop",
      totalLayOverTime: 0,
      isFreeMeal: false,
      isFreeSeat: false,
      modifiedTravelTime: "04:40",
      commaSepratedStops: [],
      commaSepratedLayoverTime: [],
      travelDaysCount: 0,
      fareFamiliyCheckBoolean: false,
      viewAllFareFamility: false,
      DomainURl: "kafilaui.traversia.net",
      SourceName: "Web",
      travelType: "International",
      typeOfTrip: "ONEWAY",
      BookingId: "TRV102469",
      totalMealPrice: 0,
      totalBaggagePrice: 0,
      totalSeatPrice: 0,
    },
  ],
  paymentGateway: {
    paymentCharges: 0,
    paymentMode: "",
  },
};
const itinerary = request.ItineraryPriceCheckResponses[0];
const segment = request.SearchRequest.Segments[0];

createAirBookingRequestBodyForCommonAPI(request, segment, itinerary);
