<?xml version="1.0" encoding="UTF-8"?>
<!--Created with WSDLGenerator 2.0.0 by Amadeus SAS-->
<!--  Amadeus Proprietary and Confidential Information: unauthorized use and disclosure strictly forbidden. 2015 - Amadeus s.a.s - All Rights Reserved.  -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:amasec="http://xml.amadeus.com/2010/06/Security_v1" xmlns:awsl="http://wsdl.amadeus.com/2010/06/ws/Link_v1" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:int="http://wsdl.amadeus.com/ServiceBookAndPrice_v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://wsdl.amadeus.com/ServiceBookAndPrice_v1_v4" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://wsdl.amadeus.com/ServiceBookAndPrice_v1_v4" name="S9ESIA_ServiceBookAndPrice_1.2_4.0">
  <wsdl:documentation>Versions: [interface: 1.2 ; technical: 4.0]</wsdl:documentation>
  <wsp:Policy wsu:Id="MessagingPolicy">
    <wsam:Addressing wsp:Optional="true">
      <wsp:Policy>
        <wsam:AnonymousResponses />
      </wsp:Policy>
    </wsam:Addressing>
  </wsp:Policy>
  <wsp:Policy wsu:Id="AmadeusPolicy">
    <wsp:PolicyReference URI="#MessagingPolicy" />
  </wsp:Policy>
  <wsdl:import namespace="http://wsdl.amadeus.com/ServiceBookAndPrice_v1" location="ServiceBookAndPrice_1.2.wsdl" />
  <wsdl:types>
    <xs:schema>
      <xs:import schemaLocation="AMA/2012B/AMA_WS_Session.xsd" namespace="http://xml.amadeus.com/2010/06/Session_v3" />
      <xs:import schemaLocation="AMA_WSLink.xsd" namespace="http://wsdl.amadeus.com/2010/06/ws/Link_v1" />
      <xs:import schemaLocation="AMA/2012B/AMA_SecurityHostedUser.xsd" namespace="http://xml.amadeus.com/2010/06/Security_v1" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="Session_3.000">
    <wsdl:part name="session" element="awsse:Session" />
  </wsdl:message>
  <wsdl:message name="TransactionFlowLink_1.0">
    <wsdl:part name="link" element="awsl:TransactionFlowLink" />
  </wsdl:message>
  <wsdl:message name="AMA_SecurityHostedUser_1.000">
    <wsdl:part name="security" element="amasec:AMA_SecurityHostedUser" />
  </wsdl:message>
  <wsdl:binding name="ServiceBookAndPrice_Binding" type="int:ServiceBookAndPrice_PT">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Service_BookPriceProduct">
      <soap:operation soapAction="http://webservices.amadeus.com/Service_BookPriceProduct_1.1" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
        <soap:header message="tns:AMA_SecurityHostedUser_1.000" part="security" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Service_BookPriceService">
      <soap:operation soapAction="http://webservices.amadeus.com/Service_BookPriceService_1.1" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
        <soap:header message="tns:AMA_SecurityHostedUser_1.000" part="security" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ServiceBookAndPrice_Service">
    <wsdl:port binding="tns:ServiceBookAndPrice_Binding" name="ServiceBookAndPrice_Port">
      <wsp:PolicyReference URI="#AmadeusPolicy" />
      <soap:address location="https://nodeD3.test.webservices.amadeus.com/1ASIWSIAS9E" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
<!--1F8B08000000000000006D8DCB0AC2301045F7FD8A592AD232AD0F24BBAA500A0A850A5D877484603309D350D0AF37E8D6DD85C33DA72126D1D17A86681DCD51BBA0A0C26A97E321C73D0C3432CDA37E4189AA3CA8ED119ADB7D83A810B3A1BF5CA1F929BCC042322753FA175860769E2C71041DC264CDB7A1A0B7FA1DC586C27807ABBEADD7495277C0DA51A2248B3574F2FE59F3D849DA59CB91E4A1CD7F0C65F501047716FFC3000000-->
