module.exports.Config = {
  // Mode (LIVE or TEST)
  MODE: "TEST",
  TEST: {
    baseURL: "https://kafilaui.traversia.net", // frontend
    baseURLBackend: "https://kafila.traversia.net",
    // additionalFlightsBaseURL: "http://localhost:31101/api",
    additionalFlightsBaseURL: "http://kafilaapi.traversia.net:61102/api",
    baseURLBackend: "https://kafila.traversia.net",
    IRCTC_BASE_URL: "https://stagews.irctc.co.in",
    IRCTC_MASTER_ID: "WKAFL00000",
    IRCTC_AUTH: "Basic V0tBRkwwMDAwMDpUZXN0aW5nMQ==",
    Mode: "TEST",
    lyraShopId: 99210763,
    lyraPassword: "testpassword_E3BhaoOPy3jv2LcdqKZ3n5TY0ShwiD1mkL7bl6VmhJg1l",
    phonePeClientId:"KAFILAUAT_25091813133013",
    phonePeClientSecret:"MDIyZjQyOTUtNDg4Zi00OTVmLWJkNzYtZWE1ZGY5NWU4MWI3",
    phonePeVersion:"1",
    phonePeAuthUrl:"https://api-preprod.phonepe.com/apis/pg-sandbox/v1/oauth/token",
    phonePePaymentUrl:"https://api-preprod.phonepe.com/apis/pg-sandbox/checkout/v2/pay",
    phonePePaymentDetailUrl:"https://api-preprod.phonepe.com/apis/pg-sandbox/checkout/v2/order",
  },
  LIVE: {
    baseURL: "https://agent.kafilaholidays.in", // frontend
    baseURLBackend: "https://agentapi.kafilaholidays.in",
    // additionalFlightsBaseURL: "http://localhost:31101/api",
    additionalFlightsBaseURL: "http://kflapi.kafilaholidays.in:61101/api",
    baseURLBackend: "https://agentapi.kafilaholidays.in",
    IRCTC_BASE_URL: "https://www.aps.irctc.co.in",
    IRCTC_MASTER_ID: "WKAFILA00000",
    IRCTC_AUTH: "Basic V0tBRklMQTAwMDAwOjBaZzFDMw==",
    Mode: "LIVE",
    lyraShopId: 99210763,
    lyraPassword: "prodpassword_5HDCe87tE0aGD7ZA7VrvfBdeXIXGKP7L6FKyhGYjh4Plz",
        phonePeClientId:"SU2510061057216616168064",
    phonePeClientSecret:"07a93cfb-a9df-415c-9cfa-b7beae98a2f9",
    phonePeVersion:"1",
    phonePeAuthUrl:"https://api.phonepe.com/apis/identity-manager/v1/oauth/token",
    phonePePaymentUrl:"https://api.phonepe.com/apis/pg/checkout/v2/pay",
    phonePePaymentDetailUrl:"https://api.phonepe.com/apis/pg/checkout/v2/order",
  },
  phonePeUserName:"KAFILALIVE_25091813133013",
  phonePePassword:"9S3dpYt4swiHaJD",

  TMCID:"6555f84c991eaa63cb171a9f",
  LYRAURL:"https://api.in.lyra.com/pg/rest/v1/charge",
  PORT: process.env.PORT || 3111,
  SECRET_JWT: process.env.SECRET_JWT || "kafilapanel",
  MONGODB_URL:
    process.env.MONGODB_URL ||
    "mongodb+srv://hsbhandari:fl1I9D8gtsbeHzdO@cluster0.xdzp3sk.mongodb.net/b2bportal",
  HOST: "smtp.hostinger.com",
  USER: "developer@traversia.tech",
  PASS: "Ttpl@2023",
  BASE_URL: "http://localhost:3111/api/",
  PAN_URL: "https://api.atlaskyc.com/v2/prod/verify/pan",
  GST_URL: "https://api.atlaskyc.com/v2/prod/verify/gstin",
  Adhar_URL: "https://api.atlaskyc.com/v2/prod/aadhaar/aadhaar_otp",
  AdharVerify_URl: "https://api.atlaskyc.com/v2/prod/aadhaar/aadhaar_kyc",
  HADDER_3RD_PAERT: {
    Accept: "application/json",
    Authorization:
      "Basic ay0zZmY0ZDYzNy0yY2UzLTQ2Y2UtYTAzMS0wZDEyMDAwOTM1MzE6cy1kNzlmOTk5MC1iYTBjLTRmNTctOTA5MS03NWYyZTQ1ZTA1Njk=",
  },
  GST_TOKEN: {
    Accept: "application/json",
    Authorization:
      "Basic ay0zZmY0ZDYzNy0yY2UzLTQ2Y2UtYTAzMS0wZDEyMDAwOTM1MzE6cy1kNzlmOTk5MC1iYTBjLTRmNTctOTA5MS03NWYyZTQ1ZTA1Njk=",
  },
  MAIL_CONFIG_ID: "6538c0364756928875840840",
  MONGODB_URL_2:
    "mongodb+srv://kafila:GeFi0weSeFN19FBv@cluster0.c7fohxg.mongodb.net/b2bportal",

  PAYMENT_CREDENTIALS_PAYU: {
    LIVE: {
      salt: "qg0bLpmz",
      key: "WgPtB8",
    },
    TEST: {
      salt: "osaj8q3wAIIeY3TZEAXQCkf94bqgOhyV",
      key: "tEd2mk",
    },
    Live: {
      salt: "DlSTL0cw",
      key: "HYDinl3tea",
    },
  },

  PAYMENT_CREDENTIALS_EASEBUSS: {
    LIVE: {
      salt: "qg0bLpmz",
      key: "WgPtB8",
    },
    TEST: {
      salt: "4R38IvwiV57FwVpsgOvTXBdLE4tHUXFW",
      key: "gtKFFx",
    },
  },

  EASEBUZZ_PG_URL: "https://testpay.easebuzz.in/payment/initiateLink",
  CancellationGSTRate: 5,
  apiTimeout: 40_000, // 40 s,
  AI_MEALS: [
    {
      code: "VJML",
      name: "JAIN MEAL",
      amount: 0,
      currency: "INR",
      desc: "",
      key: "AI_DOM_MEALS",
      origin: "",
      destination: "",
      airlineCode: "AI",
      flightNumber: "",
      wayType: 0,
      paid: false,
    },
    {
      code: "VGML",
      name: "VEGAN MEAL",
      amount: 0,
      currency: "INR",
      desc: "",
      key: "AI_DOM_MEALS",
      origin: "",
      destination: "",
      airlineCode: "AI",
      flightNumber: "",
      wayType: 0,
      paid: false,
    },
    {
      code: "HNML",
      name: "Hindu NON-VEGETARIAN MEAL",
      amount: 0,
      currency: "INR",
      desc: "",
      key: "AI_DOM_MEALS",
      origin: "",
      destination: "",
      airlineCode: "AI",
      flightNumber: "",
      wayType: 0,
      paid: false,
    },
    {
      code: "MOML",
      name: "Muslim NON-VEGETARIAN MEAL",
      amount: 0,
      currency: "INR",
      desc: "",
      key: "AI_DOM_MEALS",
      origin: "",
      destination: "",
      airlineCode: "AI",
      flightNumber: "",
      wayType: 0,
      paid: false,
    },
    {
      code: "FPML",
      name: "FRUIT PLATTER",
      amount: 0,
      currency: "INR",
      desc: "",
      key: "AI_DOM_MEALS",
      origin: "",
      destination: "",
      airlineCode: "AI",
      flightNumber: "",
      wayType: 0,
      paid: false,
    },
  ],
};
