let Ancl = {
    "Meals": null,
    "Baggage": [
        [
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO33LB 15KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 7560,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAclE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "813",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO33LB 15KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 7560,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAglE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO44LB 20KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 10080,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAklE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "813",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO44LB 20KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 10080,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAolE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO55LB 25KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 12600,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAslE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "813",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO55LB 25KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 12600,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAwlE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO11LB 5KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 2520,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKA0lE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "813",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO11LB 5KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 2520,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKA4lE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO22LB 10KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 5040,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKA8lE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "813",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO22LB 10KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 5040,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAAmE1mAAAAA=="
            }
        ]
    ],
    "Specials": null,
    "Seat": [
        [
            [
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-A",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-B",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-C",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Front of cabin class/compartment",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-D",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Front of cabin class/compartment",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-E",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-F",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                }
            ],
            [
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-A",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA1LGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-B",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 200,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA2LGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-C",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "PaidGeneralSeat",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA3LGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-D",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "PaidGeneralSeat",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA3LGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-E",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 200,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA2LGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-F",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA1LGqmAAAAA==",
                    "Leg": 0
                }
            ]   
        ],
        [
            [
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-A",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA5LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-B",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA5LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-C",
                    "Avlt": false,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Restricted seat - General",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA6LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-D",
                    "Avlt": false,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Restricted seat - General",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA6LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-E",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA5LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-F",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA5LGqmAAAAA==",
                    "Leg": 1
                }
            ],
            [
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-A",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA7LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-B",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 200,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA8LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-C",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "PaidGeneralSeat",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA6LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-D",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "PaidGeneralSeat",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA6LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-E",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 200,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA8LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-F",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA7LGqmAAAAA==",
                    "Leg": 1
                }
            ]
        ]
    ]
}