
let ancl = {
    Meals : [[{},{},{}]],
    Baggage : [[]],
    Seat : [
        [
           {
        "Trip": 0,
        "FCode": "AI",
        "FNo": "514",
        "FType": "32N",
        "Deck": "M",
        "Compartemnt": "",
        "Group": "0",
        "SeatCode": "4-A",
        "Avlt": true,
        "SeatRow": 4,
        "Currency": "INR",
        "SsrDesc": "Window",
        "Price": 1000,
        "DDate": "2024-03-25",
        "Src": "DEL",
        "Des": "BLR",
        "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
        "Leg": 0
           },
           {
        "Trip": 0,
        "FCode": "AI",
        "FNo": "514",
        "FType": "32N",
        "Deck": "M",
        "Compartemnt": "",
        "Group": "0",
        "SeatCode": "4-B",
        "Avlt": true,
        "SeatRow": 4,
        "Currency": "INR",
        "SsrDesc": "Center seat (not window, not aisle)",
        "Price": 1000,
        "DDate": "2024-03-25",
        "Src": "DEL",
        "Des": "BLR",
        "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
        "Leg": 0
           },{
            "Trip" : 0,
            "FCode" : "AI",
            "FNo" : "514",
            "FType" : "32N",
            "Deck" : "M",
            "Compartemnt" : "",
            "Group" : "0",
            "SeatCode" : "4-C",
            "Avlt" : true,
            "SeatRow" : 4,
            "Currency" : "INR",
            "SsrDesc" : ""
           }
        ],
        [
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "FType": "32N",
                "Deck": "M",
                "Compartemnt": "",
                "Group": "0",
                "SeatCode": "5-A",
                "Avlt": true,
                "SeatRow": 5,
                "Currency": "INR",
                "SsrDesc": "Window",
                "Price": 375,
                "DDate": "2024-03-25",
                "Src": "DEL",
                "Des": "BLR",
                "OI": "QEhxZ0TqWDKA1LGqmAAAAA==",
                "Leg": 0
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "FType": "32N",
                "Deck": "M",
                "Compartemnt": "",
                "Group": "0",
                "SeatCode": "5-B",
                "Avlt": true,
                "SeatRow": 5,
                "Currency": "INR",
                "SsrDesc": "Center seat (not window, not aisle)",
                "Price": 200,
                "DDate": "2024-03-25",
                "Src": "DEL",
                "Des": "BLR",
                "OI": "QEhxZ0TqWDKA2LGqmAAAAA==",
                "Leg": 0
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "FType": "32N",
                "Deck": "M",
                "Compartemnt": "",
                "Group": "0",
                "SeatCode": "5-C",
                "Avlt": true,
                "SeatRow": 5,
                "Currency": "INR",
                "SsrDesc": "PaidGeneralSeat",
                "Price": 375,
                "DDate": "2024-03-25",
                "Src": "DEL",
                "Des": "BLR",
                "OI": "QEhxZ0TqWDKA3LGqmAAAAA==",
                "Leg": 0
            }
        ],[],[]]


}