let Ancl = {
    "Meals": null,
    "Baggage": [
        [
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO33LB 15KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 7560,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAclE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "813",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO33LB 15KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 7560,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAglE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO44LB 20KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 10080,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAklE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "813",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO44LB 20KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 10080,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAolE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO55LB 25KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 12600,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAslE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "813",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO55LB 25KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 12600,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAwlE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO11LB 5KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 2520,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKA0lE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "813",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO11LB 5KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 2520,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKA4lE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "514",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO22LB 10KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 5040,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKA8lE1mAAAAA=="
            },
            {
                "Trip": 0,
                "FCode": "AI",
                "FNo": "813",
                "SsrCode": "XBAG",
                "SsrDesc": "UPTO22LB 10KG BAGGAGE",
                "Complmnt": false,
                "Currency": "INR",
                "Price": 5040,
                "Src": "DEL",
                "Des": "BLR",
                "SsrFor": "JOURNEY",
                "OI": "ThfxZ0VqWDKAAmE1mAAAAA=="
            }
        ]
    ],
    "Specials": null,
    "Seat": [
        [
            [
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-A",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-B",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-C",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Front of cabin class/compartment",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-D",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Front of cabin class/compartment",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-E",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-F",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKAzLGqmAAAAA==",
                    "Leg": 0
                }
            ],
            [
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-A",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA1LGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-B",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 200,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA2LGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-C",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "PaidGeneralSeat",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA3LGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-D",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "PaidGeneralSeat",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA3LGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-E",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 200,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA2LGqmAAAAA==",
                    "Leg": 0
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "514",
                    "FType": "32N",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-F",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA1LGqmAAAAA==",
                    "Leg": 0
                }
            ]   
        ],
        [
            [
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-A",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA5LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-B",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA5LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-C",
                    "Avlt": false,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Restricted seat - General",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA6LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-D",
                    "Avlt": false,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Restricted seat - General",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA6LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-E",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA5LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "4-F",
                    "Avlt": true,
                    "SeatRow": 4,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 1000,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA5LGqmAAAAA==",
                    "Leg": 1
                }
            ],
            [
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-A",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA7LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-B",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 200,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA8LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-C",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "PaidGeneralSeat",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA6LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-D",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "PaidGeneralSeat",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA6LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-E",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Center seat (not window, not aisle)",
                    "Price": 200,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA8LGqmAAAAA==",
                    "Leg": 1
                },
                {
                    "Trip": 0,
                    "FCode": "AI",
                    "FNo": "813",
                    "FType": "321",
                    "Deck": "M",
                    "Compartemnt": "",
                    "Group": "0",
                    "SeatCode": "5-F",
                    "Avlt": true,
                    "SeatRow": 5,
                    "Currency": "INR",
                    "SsrDesc": "Window",
                    "Price": 375,
                    "DDate": "2024-03-25",
                    "Src": "DEL",
                    "Des": "BLR",
                    "OI": "QEhxZ0TqWDKA7LGqmAAAAA==",
                    "Leg": 1
                }
            ]
        ]
    ]
};
let res = {
    "AirSegments": [
        {
            "SeatRows": [
                {
                    "Number": "1",
                    "Facilities": [
                        {
                            "Type": "Seat",
                            "SeatCode": "1A",
                            "Availability": "Open",
                            "Paid": true,
                            "Characteristics": [
                                "WINDOW"
                            ],
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 850.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Seat",
                            "SeatCode": "1B",
                            "Availability": "Open",
                            "Paid": true,
                            "Characteristics": null,
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 600.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Seat",
                            "SeatCode": "1C",
                            "Availability": "Open",
                            "Paid": true,
                            "Characteristics": [
                                "AISLE"
                            ],
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 850.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Aisle",
                            "SeatCode": null,
                            "Availability": null,
                            "Paid": false,
                            "Characteristics": null,
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 0.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Seat",
                            "SeatCode": "1D",
                            "Availability": "Open",
                            "Paid": true,
                            "Characteristics": [
                                "AISLE"
                            ],
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 850.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Seat",
                            "SeatCode": "1E",
                            "Availability": "Open",
                            "Paid": true,
                            "Characteristics": null,
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 600.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Seat",
                            "SeatCode": "1F",
                            "Availability": "Open",
                            "Paid": true,
                            "Characteristics": [
                                "WINDOW"
                            ],
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 850.0,
                            "ProviderDefinedType": null
                        }
                    ]
                },
                {
                    "Number": "2",
                    "Facilities": [
                        {
                            "Type": "Seat",
                            "SeatCode": "2A",
                            "Availability": "Open",
                            "Paid": false,
                            "Characteristics": [
                                "WINDOW"
                            ],
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 0.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Seat",
                            "SeatCode": "2B",
                            "Availability": "Open",
                            "Paid": false,
                            "Characteristics": null,
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 0.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Seat",
                            "SeatCode": "2C",
                            "Availability": "Open",
                            "Paid": false,
                            "Characteristics": [
                                "AISLE"
                            ],
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 0.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Aisle",
                            "SeatCode": null,
                            "Availability": null,
                            "Paid": false,
                            "Characteristics": null,
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 0.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Seat",
                            "SeatCode": "2D",
                            "Availability": "Open",
                            "Paid": false,
                            "Characteristics": [
                                "AISLE"
                            ],
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 0.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Seat",
                            "SeatCode": "2E",
                            "Availability": "Open",
                            "Paid": false,
                            "Characteristics": null,
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 0.0,
                            "ProviderDefinedType": null
                        },
                        {
                            "Type": "Seat",
                            "SeatCode": "2F",
                            "Availability": "Open",
                            "Paid": false,
                            "Characteristics": [
                                "WINDOW"
                            ],
                            "Key": null,
                            "Currency": null,
                            "TotalPrice": 0.0,
                            "ProviderDefinedType": null
                        }
                    ]
                },
            ],
            "IsConnect": false,
            "AirlineCode": "QP",
            "AirlineName": "Akasa Air",
            "Class": "",
            "CabinClass": "",
            "BookingCounts": "",
            "NoSeats": 0,
            "FltNum": "1607",
            "EquipType": "7MA",
            "FlyingTime": null,
            "TravelTime": null,
            "TechStopOver": 0,
            "Status": "",
            "OperatingCarrier": null,
            "MarketingCarrier": null,
            "BaggageInfo": "",
            "HandBaggage": "7 KG",
            "TransitTime": null,
            "MealCode": null,
            "Key": "",
            "Distance": "",
            "ETicket": "",
            "ChangeOfPlane": "",
            "ParticipantLevel": "",
            "OptionalServicesIndicator": false,
            "AvailabilitySource": "",
            "Group": "",
            "LinkAvailability": "",
            "PolledAvailabilityOption": "",
            "FareBasisCode": "",
            "HostTokenRef": "",
            "APISRequirementsRef": "",
            "Departure": {
                "Terminal": null,
                "Date": "28/02/2024",
                "Time": "11:35",
                "Day": null,
                "DateTimeStamp": null,
                "Code": "DEL",
                "Name": "Indira Gandhi International Airport",
                "CityCode": "DEL",
                "CityName": "Delhi",
                "CountryCode": "IN",
                "CountryName": "India"
            },
            "Arrival": {
                "Terminal": null,
                "Date": "28/02/2024",
                "Time": "12:55",
                "Day": null,
                "DateTimeStamp": null,
                "Code": "AYJ",
                "Name": "Maharishi Valmiki International Airport Ayodhya Dham",
                "CityCode": "",
                "CityName": "Ayodhya",
                "CountryCode": "IN",
                "CountryName": "India"
            }
        }
    ],
}

function changeResponse (data) {

}