const mongoose = require("mongoose");

const seriesDepartureSchema = new mongoose.Schema({
  pnr: String,
  account_code: String,
  flight_type: String,
  cabin_class: String,
  trip_type: String,
  fare_name: String,
  aircraft_type: String,
  airline_code: String,
  flight_number: Number,
  origin_airport_code: String,
  origin_airport_terminal: String,
  destination_airport_code: String,
  destination_airport_terminal: String,
  departure_date: String,
  departure_time: String,
  arrival_date: String,
  arrival_time: String,
  distance: Number,
  travel_time: String,
  stops: Number,
  total_seats: Number,
  available_seats: Number,
  rbd: String,
  baseamount: Number,
  fuelsurchg: Number,
  taxamount: Number,
  baseamountchd: Number,
  fuelsurchgchd: Number,
  taxamountchd: Number,
  baseamountinf: Number,
  fuelsurchginf: Number,
  taxamountinf: Number,
  carryonallowance: String,
  baggageallowance: String,
  isrefundable: Boolean,
  cancelpenalty: String,
  changepenalty: String,
  isactive: Boolean,
  baseamountcost: Number,
  fuelsurchgcost: Number,
  taxamountcost: Number,
  baseamountchdcost: Number,
  fuelsurchgchdcost: Number,
  taxamountchdcost: Number,
  baseamountinfcost: Number,
  fuelsurchginfcost: Number,
  taxamountinfcost: Number,
  airline_code_0: String,
  boundtype_0: Number,
  flightnumber_0: Number,
  origin_0: String,
  oterm_0: String,
  destination_0: String,
  dterm_0: String,
  departuredate_0: String,
  departuretime_0: String,
  arrivaldate_0: String,
  arrivaltime_0: String,
  flyingtime_0: String,
  distance_0: Number,
  baggage_name_0: String,
  baggage_charge_0: Number,
  meal_0: String,
  meal_charge_0: Number,
  flights: [{
      airline_code: String,
      boundtype: Number,
      flightnumber: Number,
      origin: String,
      oterm: String,
      destination: String,
      dterm: String,
      departuredate: String,
      departuretime: String,
      arrivaldate: String,
      arrivaltime: String,
      flyingtime: String,
      distance: Number,
  }],
  baggage: [{
      name: String,
      charge: Number,
  }],
  meal: [{
      name: String,
      charge: Number,
  }],
  companyId: {
    type: mongoose.Schema.Types.ObjectId,
    ref : 'Company'
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref : 'User'
  },
  groupId: {
   type : String
  },
  seriesId: String,
  status: Boolean,
  autoTicketing: Boolean,
  supplierCode : String
});
const seriesDeparture = mongoose.model("seriesDeparture", seriesDepartureSchema);
module.exports = seriesDeparture;